### ISSUE TITLE
Sketch 50 doesn't want to show the plugin

### ISSUE THREAD

**Issue by ivancucer** [mathieudutour/rough-sketch#1]
Hey @mathieudutour 👋

Thank you for the plugin ❤️ Theoretically, it looks cool, but Sketch 50 doesn't want to show one 🤔

![2018-04-14 21-21-45](https://user-images.githubusercontent.com/2349195/38771834-6e36120e-402a-11e8-978c-7b676a9de5cb.jpg)

Any ideas ? 🤓

Thanks in advance! 🙌

Ivan

**Comment by mathieudutour** [comment]
somehow the publication failed. Can you try with the versionn 0.1.2: https://github.com/mathieudutour/rough-sketch/releases/tag/v0.1.2?

**Comment by ivancucer** [comment]
Works! Thank you 👍

FYI https://github.com/mathieudutour/rough-sketch/issues/2
