### ISSUE TITLE
Without artboard

### ISSUE THREAD

**Issue by ivancucer** [mathieudutour/rough-sketch#2]
Hey @mathieudutour 

The plugin doesn't work properly with shapes without artboard 🤓

Ivan

**Comment by mathieudutour** [comment]
Ah yes it needs to be in a group or an art board or something. 

It can probably be fixed, will see tomorrow

**Comment by mathieudutour** [comment]
it should be fixed in 0.1.3

**Comment by ivancucer** [comment]
Nope, same thing here 🤔

**Comment by mathieudutour** [comment]
Hum weird, what exactly is happening?

**Comment by ivancucer** [comment]
![issue](https://user-images.githubusercontent.com/2349195/38780422-30058c10-40d6-11e8-94f2-236d374ad7d7.gif)

**Comment by onglette** [comment]
Just tried this plugin but sadly, nothing happened when i applied the plugin to a rectangle

**Comment by mathieudutour** [comment]
should be fine with v0.1.5
