### ISSUE TITLE
Broken in Sketch 59?

### ISSUE THREAD

**Issue by ben5516** [mathieudutour/rough-sketch#8]
Installed this plugin but it's not working for me in Sketch 59 (rough v 2.0)

![rough_example2](https://user-images.githubusercontent.com/53109/67123368-bcc65580-f1b5-11e9-98a2-aef52f6c276e.gif)

**Comment by href** [comment]
Same for me.

**Comment by melissamcewen** [comment]
Same

**Comment by dmaloney01** [comment]
Same for me as well.

**Comment by mathieudutour** [comment]
should be fixed in 0.2.1
